"""ポケモン名マッピング（日本語名→英語名・図鑑番号）.

Data source: pokemon.com / pokemongo-get.com
"""

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class PokemonNameEntry:
    """ポケモン名エントリ.

    Attributes:
        name_ja: 日本語名
        name_en: 英語名
        dex: 図鑑番号
    """

    name_ja: str
    name_en: str
    dex: int


# 日本語名 -> (英語名, 図鑑番号) マッピング
_POKEMON_NAME_MAP: Final[dict[str, tuple[str, int]]] = {
    # --- Gen 1 (001-151) ---
    "フシギダネ": ("Bulbasaur", 1),
    "フシギソウ": ("Ivysaur", 2),
    "フシギバナ": ("Venusaur", 3),
    "フシギバナ(キョダイ)": ("Venusaur (Gigantamax)", 3),
    "ヒトカゲ": ("Charmander", 4),
    "リザード": ("Charmeleon", 5),
    "リザードン": ("Charizard", 6),
    "リザードン(キョダイ)": ("Charizard (Gigantamax)", 6),
    "ゼニガメ": ("Squirtle", 7),
    "カメール": ("Wartortle", 8),
    "カメックス": ("Blastoise", 9),
    "カメックス(キョダイ)": ("Blastoise (Gigantamax)", 9),
    "キャタピー": ("Caterpie", 10),
    "トランセル": ("Metapod", 11),
    "バタフリー": ("Butterfree", 12),
    "バタフリー(キョダイ)": ("Butterfree (Gigantamax)", 12),
    "ビードル": ("Weedle", 13),
    "コクーン": ("Kakuna", 14),
    "スピアー": ("Beedrill", 15),
    "ポッポ": ("Pidgey", 16),
    "ピジョン": ("Pidgeotto", 17),
    "ピジョット": ("Pidgeot", 18),
    "コラッタ": ("Rattata", 19),
    "コラッタ(アローラ)": ("Rattata (Alolan)", 19),
    "ラッタ": ("Raticate", 20),
    "ラッタ(アローラ)": ("Raticate (Alolan)", 20),
    "オニスズメ": ("Spearow", 21),
    "オニドリル": ("Fearow", 22),
    "アーボ": ("Ekans", 23),
    "アーボック": ("Arbok", 24),
    "ピカチュウ": ("Pikachu", 25),
    "ピカチュウ(マスクド)": ("Pikachu (Libre)", 25),
    "ピカチュウ(そらをとぶ)": ("Pikachu (Flying)", 25),
    "ピカチュウ(かりゆし)": ("Pikachu (Kariyushi)", 25),
    "ピカチュウ(アイドル)": ("Pikachu (Pop Star)", 25),
    "ピカチュウ(ハードロック)": ("Pikachu (Rock Star)", 25),
    "ピカチュウ(そらをとぶ5周年)": ("Pikachu (5th Anniversary Flying)", 25),
    "ピカチュウ(ドクター)": ("Pikachu (PhD)", 25),
    "ピカチュウ(キャプテン帽子)": ("Pikachu (Captain Hat)", 25),
    "ライチュウ": ("Raichu", 26),
    "ライチュウ(アローラ)": ("Raichu (Alolan)", 26),
    "サンド": ("Sandshrew", 27),
    "サンド(アローラ)": ("Sandshrew (Alolan)", 27),
    "サンドパン": ("Sandslash", 28),
    "サンドパン(アローラ)": ("Sandslash (Alolan)", 28),
    "ニドラン♀": ("Nidoran Female", 29),
    "ニドリーナ": ("Nidorina", 30),
    "ニドクイン": ("Nidoqueen", 31),
    "ニドラン♂": ("Nidoran Male", 32),
    "ニドリーノ": ("Nidorino", 33),
    "ニドキング": ("Nidoking", 34),
    "ピッピ": ("Clefairy", 35),
    "ピクシー": ("Clefable", 36),
    "ロコン": ("Vulpix", 37),
    "ロコン(アローラ)": ("Vulpix (Alolan)", 37),
    "キュウコン": ("Ninetales", 38),
    "キュウコン(アローラ)": ("Ninetales (Alolan)", 38),
    "プリン": ("Jigglypuff", 39),
    "プクリン": ("Wigglytuff", 40),
    "ズバット": ("Zubat", 41),
    "ゴルバット": ("Golbat", 42),
    "ナゾノクサ": ("Oddish", 43),
    "クサイハナ": ("Gloom", 44),
    "ラフレシア": ("Vileplume", 45),
    "パラス": ("Paras", 46),
    "パラセクト": ("Parasect", 47),
    "コンパン": ("Venonat", 48),
    "モルフォン": ("Venomoth", 49),
    "ディグダ": ("Diglett", 50),
    "ディグダ(アローラ)": ("Diglett (Alolan)", 50),
    "ダグトリオ": ("Dugtrio", 51),
    "ダグトリオ(アローラ)": ("Dugtrio (Alolan)", 51),
    "ニャース": ("Meowth", 52),
    "ニャース(アローラ)": ("Meowth (Alolan)", 52),
    "ニャース(ガラル)": ("Meowth (Galarian)", 52),
    "ペルシアン": ("Persian", 53),
    "ペルシアン(アローラ)": ("Persian (Alolan)", 53),
    "コダック": ("Psyduck", 54),
    "ゴルダック": ("Golduck", 55),
    "マンキー": ("Mankey", 56),
    "オコリザル": ("Primeape", 57),
    "ガーディ": ("Growlithe", 58),
    "ガーディ(ヒスイ)": ("Growlithe (Hisuian)", 58),
    "ウインディ": ("Arcanine", 59),
    "ウインディ(ヒスイ)": ("Arcanine (Hisuian)", 59),
    "ニョロモ": ("Poliwag", 60),
    "ニョロゾ": ("Poliwhirl", 61),
    "ニョロボン": ("Poliwrath", 62),
    "ケーシィ": ("Abra", 63),
    "ユンゲラー": ("Kadabra", 64),
    "フーディン": ("Alakazam", 65),
    "ワンリキー": ("Machop", 66),
    "ゴーリキー": ("Machoke", 67),
    "カイリキー": ("Machamp", 68),
    "カイリキー(キョダイ)": ("Machamp (Gigantamax)", 68),
    "マダツボミ": ("Bellsprout", 69),
    "ウツドン": ("Weepinbell", 70),
    "ウツボット": ("Victreebel", 71),
    "メノクラゲ": ("Tentacool", 72),
    "ドククラゲ": ("Tentacruel", 73),
    "イシツブテ": ("Geodude", 74),
    "イシツブテ(アローラ)": ("Geodude (Alolan)", 74),
    "ゴローン": ("Graveler", 75),
    "ゴローン(アローラ)": ("Graveler (Alolan)", 75),
    "ゴローニャ": ("Golem", 76),
    "ゴローニャ(アローラ)": ("Golem (Alolan)", 76),
    "ポニータ": ("Ponyta", 77),
    "ポニータ(ガラル)": ("Ponyta (Galarian)", 77),
    "ギャロップ": ("Rapidash", 78),
    "ギャロップ(ガラル)": ("Rapidash (Galarian)", 78),
    "ヤドン": ("Slowpoke", 79),
    "ヤドン(ガラル)": ("Slowpoke (Galarian)", 79),
    "ヤドラン": ("Slowbro", 80),
    "ヤドラン(ガラル)": ("Slowbro (Galarian)", 80),
    "コイル": ("Magnemite", 81),
    "レアコイル": ("Magneton", 82),
    "カモネギ": ("Farfetch'd", 83),
    "カモネギ(ガラル)": ("Farfetch'd (Galarian)", 83),
    "ドードー": ("Doduo", 84),
    "ドードリオ": ("Dodrio", 85),
    "パウワウ": ("Seel", 86),
    "ジュゴン": ("Dewgong", 87),
    "ベトベター": ("Grimer", 88),
    "ベトベター(アローラ)": ("Grimer (Alolan)", 88),
    "ベトベトン": ("Muk", 89),
    "ベトベトン(アローラ)": ("Muk (Alolan)", 89),
    "シェルダー": ("Shellder", 90),
    "パルシェン": ("Cloyster", 91),
    "ゴース": ("Gastly", 92),
    "ゴースト": ("Haunter", 93),
    "ゲンガー": ("Gengar", 94),
    "ゲンガー(キョダイ)": ("Gengar (Gigantamax)", 94),
    "イワーク": ("Onix", 95),
    "スリープ": ("Drowzee", 96),
    "スリーパー": ("Hypno", 97),
    "クラブ": ("Krabby", 98),
    "キングラー": ("Kingler", 99),
    "キングラー(キョダイ)": ("Kingler (Gigantamax)", 99),
    "ビリリダマ": ("Voltorb", 100),
    "ビリリダマ(ヒスイ)": ("Voltorb (Hisuian)", 100),
    "マルマイン": ("Electrode", 101),
    "マルマイン(ヒスイ)": ("Electrode (Hisuian)", 101),
    "タマタマ": ("Exeggcute", 102),
    "ナッシー": ("Exeggutor", 103),
    "ナッシー(アローラ)": ("Exeggutor (Alolan)", 103),
    "カラカラ": ("Cubone", 104),
    "ガラガラ": ("Marowak", 105),
    "ガラガラ(アローラ)": ("Marowak (Alolan)", 105),
    "サワムラー": ("Hitmonlee", 106),
    "エビワラー": ("Hitmonchan", 107),
    "ベロリンガ": ("Lickitung", 108),
    "ドガース": ("Koffing", 109),
    "マタドガス": ("Weezing", 110),
    "マタドガス(ガラル)": ("Weezing (Galarian)", 110),
    "サイホーン": ("Rhyhorn", 111),
    "サイドン": ("Rhydon", 112),
    "ラッキー": ("Chansey", 113),
    "モンジャラ": ("Tangela", 114),
    "ガルーラ": ("Kangaskhan", 115),
    "タッツー": ("Horsea", 116),
    "シードラ": ("Seadra", 117),
    "トサキント": ("Goldeen", 118),
    "アズマオウ": ("Seaking", 119),
    "ヒトデマン": ("Staryu", 120),
    "スターミー": ("Starmie", 121),
    "バリヤード": ("Mr. Mime", 122),
    "バリヤード(ガラル)": ("Mr. Mime (Galarian)", 122),
    "ストライク": ("Scyther", 123),
    "ルージュラ": ("Jynx", 124),
    "エレブー": ("Electabuzz", 125),
    "ブーバー": ("Magmar", 126),
    "カイロス": ("Pinsir", 127),
    "ケンタロス": ("Tauros", 128),
    "ケンタロス(パルデア・コンバット)": ("Tauros (Paldean Combat)", 128),
    "ケンタロス(パルデア・ブレイズ)": ("Tauros (Paldean Blaze)", 128),
    "ケンタロス(パルデア・ウォーター)": ("Tauros (Paldean Aqua)", 128),
    "コイキング": ("Magikarp", 129),
    "ギャラドス": ("Gyarados", 130),
    "ラプラス": ("Lapras", 131),
    "ラプラス(キョダイ)": ("Lapras (Gigantamax)", 131),
    "メタモン": ("Ditto", 132),
    "イーブイ": ("Eevee", 133),
    "シャワーズ": ("Vaporeon", 134),
    "サンダース": ("Jolteon", 135),
    "ブースター": ("Flareon", 136),
    "ポリゴン": ("Porygon", 137),
    "オムナイト": ("Omanyte", 138),
    "オムスター": ("Omastar", 139),
    "カブト": ("Kabuto", 140),
    "カブトプス": ("Kabutops", 141),
    "プテラ": ("Aerodactyl", 142),
    "カビゴン": ("Snorlax", 143),
    "カビゴン(キョダイ)": ("Snorlax (Gigantamax)", 143),
    "フリーザー": ("Articuno", 144),
    "フリーザー(ガラル)": ("Articuno (Galarian)", 144),
    "サンダー": ("Zapdos", 145),
    "サンダー(ガラル)": ("Zapdos (Galarian)", 145),
    "ファイヤー": ("Moltres", 146),
    "ファイヤー(ガラル)": ("Moltres (Galarian)", 146),
    "ミニリュウ": ("Dratini", 147),
    "ハクリュー": ("Dragonair", 148),
    "カイリュー": ("Dragonite", 149),
    "ミュウツー": ("Mewtwo", 150),
    "ミュウツー(アーマード)": ("Mewtwo (Armored)", 150),
    "ミュウ": ("Mew", 151),
    # --- Gen 2 (152-251) ---
    "チコリータ": ("Chikorita", 152),
    "ベイリーフ": ("Bayleef", 153),
    "メガニウム": ("Meganium", 154),
    "ヒノアラシ": ("Cyndaquil", 155),
    "マグマラシ": ("Quilava", 156),
    "バクフーン": ("Typhlosion", 157),
    "バクフーン(ヒスイ)": ("Typhlosion (Hisuian)", 157),
    "ワニノコ": ("Totodile", 158),
    "アリゲイツ": ("Croconaw", 159),
    "オーダイル": ("Feraligatr", 160),
    "オタチ": ("Sentret", 161),
    "オオタチ": ("Furret", 162),
    "ホーホー": ("Hoothoot", 163),
    "ヨルノズク": ("Noctowl", 164),
    "レディバ": ("Ledyba", 165),
    "レディアン": ("Ledian", 166),
    "イトマル": ("Spinarak", 167),
    "アリアドス": ("Ariados", 168),
    "クロバット": ("Crobat", 169),
    "チョンチー": ("Chinchou", 170),
    "ランターン": ("Lanturn", 171),
    "ピチュー": ("Pichu", 172),
    "ピィ": ("Cleffa", 173),
    "ププリン": ("Igglybuff", 174),
    "トゲピー": ("Togepi", 175),
    "トゲチック": ("Togetic", 176),
    "ネイティ": ("Natu", 177),
    "ネイティオ": ("Xatu", 178),
    "メリープ": ("Mareep", 179),
    "モココ": ("Flaaffy", 180),
    "デンリュウ": ("Ampharos", 181),
    "キレイハナ": ("Bellossom", 182),
    "マリル": ("Marill", 183),
    "マリルリ": ("Azumarill", 184),
    "ウソッキー": ("Sudowoodo", 185),
    "ニョロトノ": ("Politoed", 186),
    "ハネッコ": ("Hoppip", 187),
    "ポポッコ": ("Skiploom", 188),
    "ワタッコ": ("Jumpluff", 189),
    "エイパム": ("Aipom", 190),
    "ヒマナッツ": ("Sunkern", 191),
    "キマワリ": ("Sunflora", 192),
    "ヤンヤンマ": ("Yanma", 193),
    "ウパー": ("Wooper", 194),
    "ウパー(パルデア)": ("Wooper (Paldean)", 194),
    "ヌオー": ("Quagsire", 195),
    "エーフィ": ("Espeon", 196),
    "ブラッキー": ("Umbreon", 197),
    "ヤミカラス": ("Murkrow", 198),
    "ヤドキング": ("Slowking", 199),
    "ヤドキング(ガラル)": ("Slowking (Galarian)", 199),
    "ムウマ": ("Misdreavus", 200),
    "アンノーン": ("Unown", 201),
    "ソーナンス": ("Wobbuffet", 202),
    "キリンリキ": ("Girafarig", 203),
    "クヌギダマ": ("Pineco", 204),
    "フォレトス": ("Forretress", 205),
    "ノコッチ": ("Dunsparce", 206),
    "グライガー": ("Gligar", 207),
    "ハガネール": ("Steelix", 208),
    "ブルー": ("Snubbull", 209),
    "グランブル": ("Granbull", 210),
    "ハリーセン": ("Qwilfish", 211),
    "ハリーセン(ヒスイ)": ("Qwilfish (Hisuian)", 211),
    "ハッサム": ("Scizor", 212),
    "ツボツボ": ("Shuckle", 213),
    "ヘラクロス": ("Heracross", 214),
    "ニューラ": ("Sneasel", 215),
    "ニューラ(ヒスイ)": ("Sneasel (Hisuian)", 215),
    "ヒメグマ": ("Teddiursa", 216),
    "リングマ": ("Ursaring", 217),
    "マグマッグ": ("Slugma", 218),
    "マグカルゴ": ("Magcargo", 219),
    "ウリムー": ("Swinub", 220),
    "イノムー": ("Piloswine", 221),
    "サニーゴ": ("Corsola", 222),
    "サニーゴ(ガラル)": ("Corsola (Galarian)", 222),
    "テッポウオ": ("Remoraid", 223),
    "オクタン": ("Octillery", 224),
    "デリバード": ("Delibird", 225),
    "マンタイン": ("Mantine", 226),
    "エアームド": ("Skarmory", 227),
    "デルビル": ("Houndour", 228),
    "ヘルガー": ("Houndoom", 229),
    "キングドラ": ("Kingdra", 230),
    "ゴマゾウ": ("Phanpy", 231),
    "ドンファン": ("Donphan", 232),
    "ポリゴン2": ("Porygon2", 233),
    "オドシシ": ("Stantler", 234),
    "ドーブル": ("Smeargle", 235),
    "バルキー": ("Tyrogue", 236),
    "カポエラー": ("Hitmontop", 237),
    "ムチュール": ("Smoochum", 238),
    "エレキッド": ("Elekid", 239),
    "ブビィ": ("Magby", 240),
    "ミルタンク": ("Miltank", 241),
    "ハピナス": ("Blissey", 242),
    "ライコウ": ("Raikou", 243),
    "エンテイ": ("Entei", 244),
    "スイクン": ("Suicune", 245),
    "ヨーギラス": ("Larvitar", 246),
    "サナギラス": ("Pupitar", 247),
    "バンギラス": ("Tyranitar", 248),
    "ルギア": ("Lugia", 249),
    "ルギア(APEX)": ("Lugia (Apex)", 249),
    "ホウオウ": ("Ho-Oh", 250),
    "ホウオウ(APEX)": ("Ho-Oh (Apex)", 250),
    "セレビィ": ("Celebi", 251),
    # --- Gen 3 (252-386) ---
    "キモリ": ("Treecko", 252),
    "ジュプトル": ("Grovyle", 253),
    "ジュカイン": ("Sceptile", 254),
    "アチャモ": ("Torchic", 255),
    "ワカシャモ": ("Combusken", 256),
    "バシャーモ": ("Blaziken", 257),
    "ミズゴロウ": ("Mudkip", 258),
    "ヌマクロー": ("Marshtomp", 259),
    "ラグラージ": ("Swampert", 260),
    "ポチエナ": ("Poochyena", 261),
    "グラエナ": ("Mightyena", 262),
    "ジグザグマ": ("Zigzagoon", 263),
    "ジグザグマ(ガラル)": ("Zigzagoon (Galarian)", 263),
    "マッスグマ": ("Linoone", 264),
    "マッスグマ(ガラル)": ("Linoone (Galarian)", 264),
    "ケムッソ": ("Wurmple", 265),
    "カラサリス": ("Silcoon", 266),
    "アゲハント": ("Beautifly", 267),
    "マユルド": ("Cascoon", 268),
    "ドクケイル": ("Dustox", 269),
    "ハスボー": ("Lotad", 270),
    "ハスブレロ": ("Lombre", 271),
    "ルンパッパ": ("Ludicolo", 272),
    "タネボー": ("Seedot", 273),
    "コノハナ": ("Nuzleaf", 274),
    "ダーテング": ("Shiftry", 275),
    "スバメ": ("Taillow", 276),
    "オオスバメ": ("Swellow", 277),
    "キャモメ": ("Wingull", 278),
    "ペリッパー": ("Pelipper", 279),
    "ラルトス": ("Ralts", 280),
    "キルリア": ("Kirlia", 281),
    "サーナイト": ("Gardevoir", 282),
    "アメタマ": ("Surskit", 283),
    "アメモース": ("Masquerain", 284),
    "キノココ": ("Shroomish", 285),
    "キノガッサ": ("Breloom", 286),
    "ナマケロ": ("Slakoth", 287),
    "ヤルキモノ": ("Vigoroth", 288),
    "ケッキング": ("Slaking", 289),
    "ツチニン": ("Nincada", 290),
    "テッカニン": ("Ninjask", 291),
    "ヌケニン": ("Shedinja", 292),
    "ゴニョニョ": ("Whismur", 293),
    "ドゴーム": ("Loudred", 294),
    "バクオング": ("Exploud", 295),
    "マクノシタ": ("Makuhita", 296),
    "ハリテヤマ": ("Hariyama", 297),
    "ルリリ": ("Azurill", 298),
    "ノズパス": ("Nosepass", 299),
    "エネコ": ("Skitty", 300),
    "エネコロロ": ("Delcatty", 301),
    "ヤミラミ": ("Sableye", 302),
    "クチート": ("Mawile", 303),
    "ココドラ": ("Aron", 304),
    "コドラ": ("Lairon", 305),
    "ボスゴドラ": ("Aggron", 306),
    "アサナン": ("Meditite", 307),
    "チャーレム": ("Medicham", 308),
    "ラクライ": ("Electrike", 309),
    "ライボルト": ("Manectric", 310),
    "プラスル": ("Plusle", 311),
    "マイナン": ("Minun", 312),
    "バルビート": ("Volbeat", 313),
    "イルミーゼ": ("Illumise", 314),
    "ロゼリア": ("Roselia", 315),
    "ゴクリン": ("Gulpin", 316),
    "マルノーム": ("Swalot", 317),
    "キバニア": ("Carvanha", 318),
    "サメハダー": ("Sharpedo", 319),
    "ホエルコ": ("Wailmer", 320),
    "ホエルオー": ("Wailord", 321),
    "ドンメル": ("Numel", 322),
    "バクーダ": ("Camerupt", 323),
    "コータス": ("Torkoal", 324),
    "バネブー": ("Spoink", 325),
    "ブーピッグ": ("Grumpig", 326),
    "パッチール": ("Spinda", 327),
    "ナックラー": ("Trapinch", 328),
    "ビブラーバ": ("Vibrava", 329),
    "フライゴン": ("Flygon", 330),
    "サボネア": ("Cacnea", 331),
    "ノクタス": ("Cacturne", 332),
    "チルット": ("Swablu", 333),
    "チルタリス": ("Altaria", 334),
    "ザングース": ("Zangoose", 335),
    "ハブネーク": ("Seviper", 336),
    "ルナトーン": ("Lunatone", 337),
    "ソルロック": ("Solrock", 338),
    "ドジョッチ": ("Barboach", 339),
    "ナマズン": ("Whiscash", 340),
    "ヘイガニ": ("Corphish", 341),
    "シザリガー": ("Crawdaunt", 342),
    "ヤジロン": ("Baltoy", 343),
    "ネンドール": ("Claydol", 344),
    "リリーラ": ("Lileep", 345),
    "ユレイドル": ("Cradily", 346),
    "アノプス": ("Anorith", 347),
    "アーマルド": ("Armaldo", 348),
    "ヒンバス": ("Feebas", 349),
    "ミロカロス": ("Milotic", 350),
    "ポワルン": ("Castform", 351),
    "ポワルン(たいよう)": ("Castform (Sunny)", 351),
    "ポワルン(あまみず)": ("Castform (Rainy)", 351),
    "ポワルン(ゆきぐも)": ("Castform (Snowy)", 351),
    "カクレオン": ("Kecleon", 352),
    "カゲボウズ": ("Shuppet", 353),
    "ジュペッタ": ("Banette", 354),
    "ヨマワル": ("Duskull", 355),
    "サマヨール": ("Dusclops", 356),
    "トロピウス": ("Tropius", 357),
    "チリーン": ("Chimecho", 358),
    "アブソル": ("Absol", 359),
    "ソーナノ": ("Wynaut", 360),
    "ユキワラシ": ("Snorunt", 361),
    "オニゴーリ": ("Glalie", 362),
    "タマザラシ": ("Spheal", 363),
    "トドグラー": ("Sealeo", 364),
    "トドゼルガ": ("Walrein", 365),
    "パールル": ("Clamperl", 366),
    "ハンテール": ("Huntail", 367),
    "サクラビス": ("Gorebyss", 368),
    "ジーランス": ("Relicanth", 369),
    "ラブカス": ("Luvdisc", 370),
    "タツベイ": ("Bagon", 371),
    "コモルー": ("Shelgon", 372),
    "ボーマンダ": ("Salamence", 373),
    "ダンバル": ("Beldum", 374),
    "メタング": ("Metang", 375),
    "メタグロス": ("Metagross", 376),
    "レジロック": ("Regirock", 377),
    "レジアイス": ("Regice", 378),
    "レジスチル": ("Registeel", 379),
    "ラティアス": ("Latias", 380),
    "ラティオス": ("Latios", 381),
    "カイオーガ": ("Kyogre", 382),
    "グラードン": ("Groudon", 383),
    "レックウザ": ("Rayquaza", 384),
    "ジラーチ": ("Jirachi", 385),
    "デオキシス": ("Deoxys", 386),
    "デオキシス(アタック)": ("Deoxys (Attack)", 386),
    "デオキシス(ディフェンス)": ("Deoxys (Defense)", 386),
    "デオキシス(スピード)": ("Deoxys (Speed)", 386),
    # --- Gen 4 (387-493) ---
    "ナエトル": ("Turtwig", 387),
    "ハヤシガメ": ("Grotle", 388),
    "ドダイトス": ("Torterra", 389),
    "ヒコザル": ("Chimchar", 390),
    "モウカザル": ("Monferno", 391),
    "ゴウカザル": ("Infernape", 392),
    "ポッチャマ": ("Piplup", 393),
    "ポッタイシ": ("Prinplup", 394),
    "エンペルト": ("Empoleon", 395),
    "ムックル": ("Starly", 396),
    "ムクバード": ("Staravia", 397),
    "ムクホーク": ("Staraptor", 398),
    "ビッパ": ("Bidoof", 399),
    "ビーダル": ("Bibarel", 400),
    "コロボーシ": ("Kricketot", 401),
    "コロトック": ("Kricketune", 402),
    "コリンク": ("Shinx", 403),
    "ルクシオ": ("Luxio", 404),
    "レントラー": ("Luxray", 405),
    "スボミー": ("Budew", 406),
    "ロズレイド": ("Roserade", 407),
    "ズガイドス": ("Cranidos", 408),
    "ラムパルド": ("Rampardos", 409),
    "タテトプス": ("Shieldon", 410),
    "トリデプス": ("Bastiodon", 411),
    "ミノムッチ": ("Burmy", 412),
    "ミノマダム(くさきのミノ)": ("Wormadam (Plant)", 413),
    "ミノマダム(すなちのミノ)": ("Wormadam (Sandy)", 413),
    "ミノマダム(ゴミのミノ)": ("Wormadam (Trash)", 413),
    "ガーメイル": ("Mothim", 414),
    "ミツハニー": ("Combee", 415),
    "ビークイン": ("Vespiquen", 416),
    "パチリス": ("Pachirisu", 417),
    "ブイゼル": ("Buizel", 418),
    "フローゼル": ("Floatzel", 419),
    "チェリンボ": ("Cherubi", 420),
    "チェリム": ("Cherrim", 421),
    "チェリム(ポジフォルム)": ("Cherrim (Sunshine)", 421),
    "カラナクシ": ("Shellos", 422),
    "トリトドン": ("Gastrodon", 423),
    "エテボース": ("Ambipom", 424),
    "フワンテ": ("Drifloon", 425),
    "フワライド": ("Drifblim", 426),
    "ミミロル": ("Buneary", 427),
    "ミミロップ": ("Lopunny", 428),
    "ムウマージ": ("Mismagius", 429),
    "ドンカラス": ("Honchkrow", 430),
    "ニャルマー": ("Glameow", 431),
    "ブニャット": ("Purugly", 432),
    "リーシャン": ("Chingling", 433),
    "スカンプー": ("Stunky", 434),
    "スカタンク": ("Skuntank", 435),
    "ドーミラー": ("Bronzor", 436),
    "ドータクン": ("Bronzong", 437),
    "ウソハチ": ("Bonsly", 438),
    "マネネ": ("Mime Jr.", 439),
    "ピンプク": ("Happiny", 440),
    "ペラップ": ("Chatot", 441),
    "ミカルゲ": ("Spiritomb", 442),
    "フカマル": ("Gible", 443),
    "ガバイト": ("Gabite", 444),
    "ガブリアス": ("Garchomp", 445),
    "ゴンベ": ("Munchlax", 446),
    "リオル": ("Riolu", 447),
    "ルカリオ": ("Lucario", 448),
    "ヒポポタス": ("Hippopotas", 449),
    "カバルドン": ("Hippowdon", 450),
    "スコルピ": ("Skorupi", 451),
    "ドラピオン": ("Drapion", 452),
    "グレッグル": ("Croagunk", 453),
    "ドクロッグ": ("Toxicroak", 454),
    "マスキッパ": ("Carnivine", 455),
    "ケイコウオ": ("Finneon", 456),
    "ネオラント": ("Lumineon", 457),
    "タマンタ": ("Mantyke", 458),
    "ユキカブリ": ("Snover", 459),
    "ユキノオー": ("Abomasnow", 460),
    "マニューラ": ("Weavile", 461),
    "ジバコイル": ("Magnezone", 462),
    "ベロベルト": ("Lickilicky", 463),
    "ドサイドン": ("Rhyperior", 464),
    "モジャンボ": ("Tangrowth", 465),
    "エレキブル": ("Electivire", 466),
    "ブーバーン": ("Magmortar", 467),
    "トゲキッス": ("Togekiss", 468),
    "メガヤンマ": ("Yanmega", 469),
    "リーフィア": ("Leafeon", 470),
    "グレイシア": ("Glaceon", 471),
    "グライオン": ("Gliscor", 472),
    "マンムー": ("Mamoswine", 473),
    "ポリゴンZ": ("Porygon-Z", 474),
    "エルレイド": ("Gallade", 475),
    "ダイノーズ": ("Probopass", 476),
    "ヨノワール": ("Dusknoir", 477),
    "ユキメノコ": ("Froslass", 478),
    "ロトム": ("Rotom", 479),
    "ロトム(ヒート)": ("Rotom (Heat)", 479),
    "ロトム(ウォッシュ)": ("Rotom (Wash)", 479),
    "ロトム(フロスト)": ("Rotom (Frost)", 479),
    "ロトム(スピン)": ("Rotom (Fan)", 479),
    "ロトム(カット)": ("Rotom (Mow)", 479),
    "ユクシー": ("Uxie", 480),
    "エムリット": ("Mesprit", 481),
    "アグノム": ("Azelf", 482),
    "ディアルガ": ("Dialga", 483),
    "ディアルガ(オリジン)": ("Dialga (Origin)", 483),
    "パルキア": ("Palkia", 484),
    "パルキア(オリジン)": ("Palkia (Origin)", 484),
    "ヒードラン": ("Heatran", 485),
    "レジギガス": ("Regigigas", 486),
    "ギラティナ": ("Giratina", 487),
    "ギラティナ(オリジン)": ("Giratina (Origin)", 487),
    "クレセリア": ("Cresselia", 488),
    "フィオネ": ("Phione", 489),
    "マナフィ": ("Manaphy", 490),
    "ダークライ": ("Darkrai", 491),
    "シェイミ": ("Shaymin", 492),
    "シェイミ(スカイ)": ("Shaymin (Sky)", 492),
    "アルセウス": ("Arceus", 493),
    # --- Gen 5 (494-649) ---
    "ビクティニ": ("Victini", 494),
    "ツタージャ": ("Snivy", 495),
    "ジャノビー": ("Servine", 496),
    "ジャローダ": ("Serperior", 497),
    "ポカブ": ("Tepig", 498),
    "チャオブー": ("Pignite", 499),
    "エンブオー": ("Emboar", 500),
    "ミジュマル": ("Oshawott", 501),
    "フタチマル": ("Dewott", 502),
    "ダイケンキ": ("Samurott", 503),
    "ダイケンキ(ヒスイ)": ("Samurott (Hisuian)", 503),
    "ミネズミ": ("Patrat", 504),
    "ミルホッグ": ("Watchog", 505),
    "ヨーテリー": ("Lillipup", 506),
    "ハーデリア": ("Herdier", 507),
    "ムーランド": ("Stoutland", 508),
    "チョロネコ": ("Purrloin", 509),
    "レパルダス": ("Liepard", 510),
    "ヤナップ": ("Pansage", 511),
    "ヤナッキー": ("Simisage", 512),
    "バオップ": ("Pansear", 513),
    "バオッキー": ("Simisear", 514),
    "ヒヤップ": ("Panpour", 515),
    "ヒヤッキー": ("Simipour", 516),
    "ムンナ": ("Munna", 517),
    "ムシャーナ": ("Musharna", 518),
    "マメパト": ("Pidove", 519),
    "ハトーボー": ("Tranquill", 520),
    "ケンホロウ": ("Unfezant", 521),
    "シママ": ("Blitzle", 522),
    "ゼブライカ": ("Zebstrika", 523),
    "ダンゴロ": ("Roggenrola", 524),
    "ガントル": ("Boldore", 525),
    "ギガイアス": ("Gigalith", 526),
    "コロモリ": ("Woobat", 527),
    "ココロモリ": ("Swoobat", 528),
    "モグリュー": ("Drilbur", 529),
    "ドリュウズ": ("Excadrill", 530),
    "タブンネ": ("Audino", 531),
    "ドッコラー": ("Timburr", 532),
    "ドテッコツ": ("Gurdurr", 533),
    "ローブシン": ("Conkeldurr", 534),
    "オタマロ": ("Tympole", 535),
    "ガマガル": ("Palpitoad", 536),
    "ガマゲロゲ": ("Seismitoad", 537),
    "ナゲキ": ("Throh", 538),
    "ダゲキ": ("Sawk", 539),
    "クルミル": ("Sewaddle", 540),
    "クルマユ": ("Swadloon", 541),
    "ハハコモリ": ("Leavanny", 542),
    "フシデ": ("Venipede", 543),
    "ホイーガ": ("Whirlipede", 544),
    "ペンドラー": ("Scolipede", 545),
    "モンメン": ("Cottonee", 546),
    "エルフーン": ("Whimsicott", 547),
    "チュリネ": ("Petilil", 548),
    "ドレディア": ("Lilligant", 549),
    "ドレディア(ヒスイ)": ("Lilligant (Hisuian)", 549),
    "バスラオ": ("Basculin", 550),
    "バスラオ(しろすじのすがた)": ("Basculin (White-Striped)", 550),
    "メグロコ": ("Sandile", 551),
    "ワルビル": ("Krokorok", 552),
    "ワルビアル": ("Krookodile", 553),
    "ダルマッカ": ("Darumaka", 554),
    "ダルマッカ(ガラル)": ("Darumaka (Galarian)", 554),
    "ヒヒダルマ": ("Darmanitan", 555),
    "ヒヒダルマ(ダルマモード)": ("Darmanitan (Zen)", 555),
    "ヒヒダルマ(ガラル)": ("Darmanitan (Galarian)", 555),
    "ヒヒダルマ(ダルマ・ガラル)": ("Darmanitan (Galarian Zen)", 555),
    "マラカッチ": ("Maractus", 556),
    "イシズマイ": ("Dwebble", 557),
    "イワパレス": ("Crustle", 558),
    "ズルッグ": ("Scraggy", 559),
    "ズルズキン": ("Scrafty", 560),
    "シンボラー": ("Sigilyph", 561),
    "デスマス": ("Yamask", 562),
    "デスマス(ガラル)": ("Yamask (Galarian)", 562),
    "デスカーン": ("Cofagrigus", 563),
    "プロトーガ": ("Tirtouga", 564),
    "アバゴーラ": ("Carracosta", 565),
    "アーケン": ("Archen", 566),
    "アーケオス": ("Archeops", 567),
    "ヤブクロン": ("Trubbish", 568),
    "ダストダス": ("Garbodor", 569),
    "ダストダス(キョダイ)": ("Garbodor (Gigantamax)", 569),
    "ゾロア": ("Zorua", 570),
    "ゾロア(ヒスイ)": ("Zorua (Hisuian)", 570),
    "ゾロアーク": ("Zoroark", 571),
    "ゾロアーク(ヒスイ)": ("Zoroark (Hisuian)", 571),
    "チラーミィ": ("Minccino", 572),
    "チラチーノ": ("Cinccino", 573),
    "ゴチム": ("Gothita", 574),
    "ゴチミル": ("Gothorita", 575),
    "ゴチルゼル": ("Gothitelle", 576),
    "ユニラン": ("Solosis", 577),
    "ダブラン": ("Duosion", 578),
    "ランクルス": ("Reuniclus", 579),
    "コアルヒー": ("Ducklett", 580),
    "スワンナ": ("Swanna", 581),
    "バニプッチ": ("Vanillite", 582),
    "バニリッチ": ("Vanillish", 583),
    "バイバニラ": ("Vanilluxe", 584),
    "シキジカ": ("Deerling", 585),
    "メブキジカ": ("Sawsbuck", 586),
    "エモンガ": ("Emolga", 587),
    "カブルモ": ("Karrablast", 588),
    "シュバルゴ": ("Escavalier", 589),
    "タマゲタケ": ("Foongus", 590),
    "モロバレル": ("Amoonguss", 591),
    "プルリル": ("Frillish", 592),
    "ブルンゲル": ("Jellicent", 593),
    "ママンボウ": ("Alomomola", 594),
    "バチュル": ("Joltik", 595),
    "デンチュラ": ("Galvantula", 596),
    "テッシード": ("Ferroseed", 597),
    "ナットレイ": ("Ferrothorn", 598),
    "ギアル": ("Klink", 599),
    "ギギアル": ("Klang", 600),
    "ギギギアル": ("Klinklang", 601),
    "シビシラス": ("Tynamo", 602),
    "シビビール": ("Eelektrik", 603),
    "シビルドン": ("Eelektross", 604),
    "リグレー": ("Elgyem", 605),
    "オーベム": ("Beheeyem", 606),
    "ヒトモシ": ("Litwick", 607),
    "ランプラー": ("Lampent", 608),
    "シャンデラ": ("Chandelure", 609),
    "キバゴ": ("Axew", 610),
    "オノンド": ("Fraxure", 611),
    "オノノクス": ("Haxorus", 612),
    "クマシュン": ("Cubchoo", 613),
    "ツンベアー": ("Beartic", 614),
    "フリージオ": ("Cryogonal", 615),
    "チョボマキ": ("Shelmet", 616),
    "アギルダー": ("Accelgor", 617),
    "マッギョ": ("Stunfisk", 618),
    "マッギョ(ガラル)": ("Stunfisk (Galarian)", 618),
    "コジョフー": ("Mienfoo", 619),
    "コジョンド": ("Mienshao", 620),
    "クリムガン": ("Druddigon", 621),
    "ゴビット": ("Golett", 622),
    "ゴルーグ": ("Golurk", 623),
    "コマタナ": ("Pawniard", 624),
    "キリキザン": ("Bisharp", 625),
    "バッフロン": ("Bouffalant", 626),
    "ワシボン": ("Rufflet", 627),
    "ウォーグル": ("Braviary", 628),
    "ウォーグル(ヒスイ)": ("Braviary (Hisuian)", 628),
    "バルチャイ": ("Vullaby", 629),
    "バルジーナ": ("Mandibuzz", 630),
    "クイタラン": ("Heatmor", 631),
    "アイアント": ("Durant", 632),
    "モノズ": ("Deino", 633),
    "ジヘッド": ("Zweilous", 634),
    "サザンドラ": ("Hydreigon", 635),
    "メラルバ": ("Larvesta", 636),
    "ウルガモス": ("Volcarona", 637),
    "コバルオン": ("Cobalion", 638),
    "テラキオン": ("Terrakion", 639),
    "ビリジオン": ("Virizion", 640),
    "トルネロス": ("Tornadus", 641),
    "トルネロス(れいじゅう)": ("Tornadus (Therian)", 641),
    "ボルトロス": ("Thundurus", 642),
    "ボルトロス(れいじゅう)": ("Thundurus (Therian)", 642),
    "レシラム": ("Reshiram", 643),
    "ゼクロム": ("Zekrom", 644),
    "ランドロス": ("Landorus", 645),
    "ランドロス(れいじゅう)": ("Landorus (Therian)", 645),
    "キュレム": ("Kyurem", 646),
    "キュレム(ホワイト)": ("Kyurem (White)", 646),
    "キュレム(ブラック)": ("Kyurem (Black)", 646),
    "ケルディオ": ("Keldeo", 647),
    "ケルディオ(かくご)": ("Keldeo (Resolute)", 647),
    "メロエッタ": ("Meloetta", 648),
    "メロエッタ(ステップ)": ("Meloetta (Pirouette)", 648),
    "ゲノセクト": ("Genesect", 649),
    "ゲノセクト(ブレイズ)": ("Genesect (Burn)", 649),
    "ゲノセクト(アクア)": ("Genesect (Douse)", 649),
    "ゲノセクト(イナズマ)": ("Genesect (Shock)", 649),
    "ゲノセクト(フリーズ)": ("Genesect (Chill)", 649),
    # --- Gen 6 (650-721) ---
    "ハリマロン": ("Chespin", 650),
    "ハリボーグ": ("Quilladin", 651),
    "ブリガロン": ("Chesnaught", 652),
    "フォッコ": ("Fennekin", 653),
    "テールナー": ("Braixen", 654),
    "マフォクシー": ("Delphox", 655),
    "ケロマツ": ("Froakie", 656),
    "ゲコガシラ": ("Frogadier", 657),
    "ゲッコウガ": ("Greninja", 658),
    "ホルビー": ("Bunnelby", 659),
    "ホルード": ("Diggersby", 660),
    "ヤヤコマ": ("Fletchling", 661),
    "ヒノヤコマ": ("Fletchinder", 662),
    "ファイアロー": ("Talonflame", 663),
    "コフキムシ": ("Scatterbug", 664),
    "コフーライ": ("Spewpa", 665),
    "ビビヨン": ("Vivillon", 666),
    "シシコ": ("Litleo", 667),
    "カエンジシ": ("Pyroar", 668),
    "フラベベ": ("Flabebe", 669),
    "フラエッテ": ("Floette", 670),
    "フラージェス": ("Florges", 671),
    "メェークル": ("Skiddo", 672),
    "ゴーゴート": ("Gogoat", 673),
    "ヤンチャム": ("Pancham", 674),
    "ゴロンダ": ("Pangoro", 675),
    "トリミアン": ("Furfrou", 676),
    "ニャスパー": ("Espurr", 677),
    "ニャオニクス(オス)": ("Meowstic (Male)", 678),
    "ニャオニクス(メス)": ("Meowstic (Female)", 678),
    "ヒトツキ": ("Honedge", 679),
    "ニダンギル": ("Doublade", 680),
    "ギルガルド(シールド)": ("Aegislash (Shield)", 681),
    "ギルガルド(ブレード)": ("Aegislash (Blade)", 681),
    "シュシュプ": ("Spritzee", 682),
    "フレフワン": ("Aromatisse", 683),
    "ペロッパフ": ("Swirlix", 684),
    "ペロリーム": ("Slurpuff", 685),
    "マーイーカ": ("Inkay", 686),
    "カラマネロ": ("Malamar", 687),
    "カメテテ": ("Binacle", 688),
    "ガメノデス": ("Barbaracle", 689),
    "クズモー": ("Skrelp", 690),
    "ドラミドロ": ("Dragalge", 691),
    "ウデッポウ": ("Clauncher", 692),
    "ブロスター": ("Clawitzer", 693),
    "エリキテル": ("Helioptile", 694),
    "エレザード": ("Heliolisk", 695),
    "チゴラス": ("Tyrunt", 696),
    "ガチゴラス": ("Tyrantrum", 697),
    "アマルス": ("Amaura", 698),
    "アマルルガ": ("Aurorus", 699),
    "ニンフィア": ("Sylveon", 700),
    "ルチャブル": ("Hawlucha", 701),
    "デデンネ": ("Dedenne", 702),
    "メレシー": ("Carbink", 703),
    "ヌメラ": ("Goomy", 704),
    "ヌメイル": ("Sliggoo", 705),
    "ヌメルゴン": ("Goodra", 706),
    "クレッフィ": ("Klefki", 707),
    "ボクレー": ("Phantump", 708),
    "オーロット": ("Trevenant", 709),
    "バケッチャ(ちいさい)": ("Pumpkaboo (Small)", 710),
    "バケッチャ(ふつう)": ("Pumpkaboo (Average)", 710),
    "バケッチャ(おおきい)": ("Pumpkaboo (Large)", 710),
    "バケッチャ(とくだい)": ("Pumpkaboo (Super)", 710),
    "パンプジン(ちいさい)": ("Gourgeist (Small)", 711),
    "パンプジン(ふつう)": ("Gourgeist (Average)", 711),
    "パンプジン(おおきい)": ("Gourgeist (Large)", 711),
    "パンプジン(とくだい)": ("Gourgeist (Super)", 711),
    "カチコール": ("Bergmite", 712),
    "クレベース": ("Avalugg", 713),
    "クレベース(ヒスイ)": ("Avalugg (Hisuian)", 713),
    "オンバット": ("Noibat", 714),
    "オンバーン": ("Noivern", 715),
    "ゼルネアス": ("Xerneas", 716),
    "イベルタル": ("Yveltal", 717),
    "ジガルデ": ("Zygarde", 718),
    "ジガルデ(１０％)": ("Zygarde (10%)", 718),
    "ジガルデ(パーフェクト)": ("Zygarde (Complete)", 718),
    "ディアンシー": ("Diancie", 719),
    "フーパ": ("Hoopa", 720),
    "フーパ(ときはなたれし)": ("Hoopa (Unbound)", 720),
    "ボルケニオン": ("Volcanion", 721),
    # --- Gen 7 (722-809) ---
    "モクロー": ("Rowlet", 722),
    "フクスロー": ("Dartrix", 723),
    "ジュナイパー": ("Decidueye", 724),
    "ジュナイパー(ヒスイ)": ("Decidueye (Hisuian)", 724),
    "ニャビー": ("Litten", 725),
    "ニャヒート": ("Torracat", 726),
    "ガオガエン": ("Incineroar", 727),
    "アシマリ": ("Popplio", 728),
    "オシャマリ": ("Brionne", 729),
    "アシレーヌ": ("Primarina", 730),
    "ツツケラ": ("Pikipek", 731),
    "ケララッパ": ("Trumbeak", 732),
    "ドデカバシ": ("Toucannon", 733),
    "ヤングース": ("Yungoos", 734),
    "デカグース": ("Gumshoos", 735),
    "アゴジムシ": ("Grubbin", 736),
    "デンヂムシ": ("Charjabug", 737),
    "クワガノン": ("Vikavolt", 738),
    "マケンカニ": ("Crabrawler", 739),
    "ケケンカニ": ("Crabominable", 740),
    "オドリドリ(めらめら)": ("Oricorio (Baile)", 741),
    "オドリドリ(ぱちぱち)": ("Oricorio (Pom-Pom)", 741),
    "オドリドリ(ふらふら)": ("Oricorio (Pa'u)", 741),
    "オドリドリ(まいまい)": ("Oricorio (Sensu)", 741),
    "アブリー": ("Cutiefly", 742),
    "アブリボン": ("Ribombee", 743),
    "イワンコ": ("Rockruff", 744),
    "イワンコ(たそがれに進化)": ("Rockruff (Dusk)", 744),
    "ルガルガン(まひる)": ("Lycanroc (Midday)", 745),
    "ルガルガン(まよなか)": ("Lycanroc (Midnight)", 745),
    "ルガルガン(たそがれ)": ("Lycanroc (Dusk)", 745),
    "ヨワシ(たんどく)": ("Wishiwashi (Solo)", 746),
    "ヨワシ(むれ)": ("Wishiwashi (School)", 746),
    "ヒドイデ": ("Mareanie", 747),
    "ドヒドイデ": ("Toxapex", 748),
    "ドロバンコ": ("Mudbray", 749),
    "バンバドロ": ("Mudsdale", 750),
    "シズクモ": ("Dewpider", 751),
    "オニシズクモ": ("Araquanid", 752),
    "カリキリ": ("Fomantis", 753),
    "ラランテス": ("Lurantis", 754),
    "ネマシュ": ("Morelull", 755),
    "マシェード": ("Shiinotic", 756),
    "ヤトウモリ": ("Salandit", 757),
    "エンニュート": ("Salazzle", 758),
    "ヌイコグマ": ("Stufful", 759),
    "キテルグマ": ("Bewear", 760),
    "アマカジ": ("Bounsweet", 761),
    "アママイコ": ("Steenee", 762),
    "アマージョ": ("Tsareena", 763),
    "キュワワー": ("Comfey", 764),
    "ヤレユータン": ("Oranguru", 765),
    "ナゲツケサル": ("Passimian", 766),
    "コソクムシ": ("Wimpod", 767),
    "グソクムシャ": ("Golisopod", 768),
    "スナバァ": ("Sandygast", 769),
    "シロデスナ": ("Palossand", 770),
    "ナマコブシ": ("Pyukumuku", 771),
    "タイプ：ヌル": ("Type: Null", 772),
    "シルヴァディ": ("Silvally", 773),
    "メテノ(りゅうせい)": ("Minior (Meteor)", 774),
    "メテノ(コア)": ("Minior (Core)", 774),
    "ネッコアラ": ("Komala", 775),
    "バクガメス": ("Turtonator", 776),
    "トゲデマル": ("Togedemaru", 777),
    "ミミッキュ": ("Mimikyu", 778),
    "ハギギシリ": ("Bruxish", 779),
    "ジジーロン": ("Drampa", 780),
    "ダダリン": ("Dhelmise", 781),
    "ジャラコ": ("Jangmo-o", 782),
    "ジャランゴ": ("Hakamo-o", 783),
    "ジャラランガ": ("Kommo-o", 784),
    "カプ・コケコ": ("Tapu Koko", 785),
    "カプ・テテフ": ("Tapu Lele", 786),
    "カプ・ブルル": ("Tapu Bulu", 787),
    "カプ・レヒレ": ("Tapu Fini", 788),
    "コスモッグ": ("Cosmog", 789),
    "コスモウム": ("Cosmoem", 790),
    "ソルガレオ": ("Solgaleo", 791),
    "ルナアーラ": ("Lunala", 792),
    "ウツロイド": ("Nihilego", 793),
    "マッシブーン": ("Buzzwole", 794),
    "フェローチェ": ("Pheromosa", 795),
    "デンジュモク": ("Xurkitree", 796),
    "テッカグヤ": ("Celesteela", 797),
    "カミツルギ": ("Kartana", 798),
    "アクジキング": ("Guzzlord", 799),
    "ネクロズマ": ("Necrozma", 800),
    "ネクロズマ(たそがれ)": ("Necrozma (Dusk Mane)", 800),
    "ネクロズマ(あかつき)": ("Necrozma (Dawn Wings)", 800),
    "マーシャドー": ("Marshadow", 802),
    "ベベノム": ("Poipole", 803),
    "アーゴヨン": ("Naganadel", 804),
    "ツンデツンデ": ("Stakataka", 805),
    "ズガドーン": ("Blacephalon", 806),
    "メルタン": ("Meltan", 808),
    "メルメタル": ("Melmetal", 809),
    # --- Gen 8 (810-905) ---
    "サルノリ": ("Grookey", 810),
    "バチンキー": ("Thwackey", 811),
    "ゴリランダー": ("Rillaboom", 812),
    "ゴリランダー(キョダイ)": ("Rillaboom (Gigantamax)", 812),
    "ヒバニー": ("Scorbunny", 813),
    "ラビフット": ("Raboot", 814),
    "エースバーン": ("Cinderace", 815),
    "エースバーン(キョダイ)": ("Cinderace (Gigantamax)", 815),
    "メッソン": ("Sobble", 816),
    "ジメレオン": ("Drizzile", 817),
    "インテレオン": ("Inteleon", 818),
    "インテレオン(キョダイ)": ("Inteleon (Gigantamax)", 818),
    "ホシガリス": ("Skwovet", 819),
    "ヨクバリス": ("Greedent", 820),
    "ココガラ": ("Rookidee", 821),
    "アオガラス": ("Corvisquire", 822),
    "アーマーガア": ("Corviknight", 823),
    "レドームシ": ("Dottler", 825),
    "イオルブ": ("Orbeetle", 826),
    "クスネ": ("Nickit", 827),
    "フォクスライ": ("Thievul", 828),
    "ヒメンカ": ("Gossifleur", 829),
    "ワタシラガ": ("Eldegoss", 830),
    "ウールー": ("Wooloo", 831),
    "バイウールー": ("Dubwool", 832),
    "カムカメ": ("Chewtle", 833),
    "カジリガメ": ("Drednaw", 834),
    "ワンパチ": ("Yamper", 835),
    "パルスワン": ("Boltund", 836),
    "タンドン": ("Rolycoly", 837),
    "トロッゴン": ("Carkol", 838),
    "セキタンザン": ("Coalossal", 839),
    "カジッチュ": ("Applin", 840),
    "アップリュー": ("Flapple", 841),
    "タルップル": ("Appletun", 842),
    "スナヘビ": ("Silicobra", 843),
    "サダイジャ": ("Sandaconda", 844),
    "ウッウ": ("Cramorant", 845),
    "サシカマス": ("Arrokuda", 846),
    "カマスジョー": ("Barraskewda", 847),
    "エレズン": ("Toxel", 848),
    "ストリンダー(ハイ)": ("Toxtricity (Amped)", 849),
    "ストリンダー(ロー)": ("Toxtricity (Low Key)", 849),
    "ストリンダー(キョダイ)": ("Toxtricity (Gigantamax)", 849),
    "ヤクデ": ("Sizzlipede", 850),
    "マルヤクデ": ("Centiskorch", 851),
    "タタッコ": ("Clobbopus", 852),
    "オトスパス": ("Grapploct", 853),
    "ヤバチャ": ("Sinistea", 854),
    "ポットデス": ("Polteageist", 855),
    "ミブリム": ("Hatenna", 856),
    "テブリム": ("Hattrem", 857),
    "ブリムオン": ("Hatterene", 858),
    "ベロバー": ("Impidimp", 859),
    "ギモー": ("Morgrem", 860),
    "オーロンゲ": ("Grimmsnarl", 861),
    "オーロンゲ(キョダイ)": ("Grimmsnarl (Gigantamax)", 861),
    "タチフサグマ": ("Obstagoon", 862),
    "ニャイキング": ("Perrserker", 863),
    "サニゴーン": ("Cursola", 864),
    "ネギガナイト": ("Sirfetch'd", 865),
    "バリコオル": ("Mr. Rime", 866),
    "デスバーン": ("Runerigus", 867),
    "マホミル": ("Milcery", 868),
    "マホイップ": ("Alcremie", 869),
    "タイレーツ": ("Falinks", 870),
    "バチンウニ": ("Pincurchin", 871),
    "ユキハミ": ("Snom", 872),
    "モスノウ": ("Frosmoth", 873),
    "イシヘンジン": ("Stonjourner", 874),
    "コオリッポ(アイス)": ("Eiscue (Ice)", 875),
    "コオリッポ(ナイス)": ("Eiscue (Noice)", 875),
    "イエッサン(オス)": ("Indeedee (Male)", 876),
    "イエッサン(メス)": ("Indeedee (Female)", 876),
    "モルペコ(まんぷく)": ("Morpeko (Full Belly)", 877),
    "モルペコ(はらぺこ)": ("Morpeko (Hangry)", 877),
    "ゾウドウ": ("Cufant", 878),
    "ダイオウドウ": ("Copperajah", 879),
    "パッチラゴン": ("Dracozolt", 880),
    "パッチルドン": ("Arctozolt", 881),
    "ウオノラゴン": ("Dracovish", 882),
    "ウオチルドン": ("Arctovish", 883),
    "ジュラルドン": ("Duraludon", 884),
    "ドラメシヤ": ("Dreepy", 885),
    "ドロンチ": ("Drakloak", 886),
    "ドラパルト": ("Dragapult", 887),
    "ザシアン(れきせんのゆうしゃ)": ("Zacian (Hero)", 888),
    "ザシアン(けんのおう)": ("Zacian (Crowned Sword)", 888),
    "ザマゼンタ(れきせんのゆうしゃ)": ("Zamazenta (Hero)", 889),
    "ザマゼンタ(たてのおう)": ("Zamazenta (Crowned Shield)", 889),
    "ムゲンダイナ": ("Eternatus", 890),
    "ムゲンダイナ(ムゲン)": ("Eternatus (Eternamax)", 890),
    "ダクマ": ("Kubfu", 891),
    "ウーラオス(いちげき)": ("Urshifu (Single Strike)", 892),
    "ウーラオス(れんげき)": ("Urshifu (Rapid Strike)", 892),
    "ザルード": ("Zarude", 893),
    "レジエレキ": ("Regieleki", 894),
    "レジドラゴ": ("Regidrago", 895),
    "ブリザポス": ("Glastrier", 896),
    "レイスポス": ("Spectrier", 897),
    "バドレックス": ("Calyrex", 898),
    "バドレックス(はくば)": ("Calyrex (Ice Rider)", 898),
    "バドレックス(こくば)": ("Calyrex (Shadow Rider)", 898),
    "アヤシシ": ("Wyrdeer", 899),
    "バサギリ": ("Kleavor", 900),
    "ガチグマ": ("Ursaluna", 901),
    "オオニューラ": ("Sneasler", 903),
    "ハリーマン": ("Overqwil", 904),
    "ラブトロス": ("Enamorus", 905),
    # --- Gen 9 (906-1025) ---
    "ニャオハ": ("Sprigatito", 906),
    "ニャローテ": ("Floragato", 907),
    "マスカーニャ": ("Meowscarada", 908),
    "ホゲータ": ("Fuecoco", 909),
    "アチゲータ": ("Crocalor", 910),
    "ラウドボーン": ("Skeledirge", 911),
    "クワッス": ("Quaxly", 912),
    "ウェルカモ": ("Quaxwell", 913),
    "ウェーニバル": ("Quaquaval", 914),
    "グルトン": ("Lechonk", 915),
    "パフュートン(オス)": ("Oinkologne (Male)", 916),
    "パフュートン(メス)": ("Oinkologne (Female)", 916),
    "タマンチュラ": ("Tarountula", 917),
    "ワナイダー": ("Spidops", 918),
    "マメバッタ": ("Nymble", 919),
    "エクスレッグ": ("Lokix", 920),
    "パモ": ("Pawmi", 921),
    "パモット": ("Pawmo", 922),
    "パーモット": ("Pawmot", 923),
    "ワッカネズミ": ("Tandemaus", 924),
    "イッカネズミ": ("Maushold", 925),
    "パピモッチ": ("Fidough", 926),
    "バウッツェル": ("Dachsbun", 927),
    "ミニーブ": ("Smoliv", 928),
    "オリーニョ": ("Dolliv", 929),
    "オリーヴァ": ("Arboliva", 930),
    "イキリンコ": ("Squawkabilly", 931),
    "コジオ": ("Nacli", 932),
    "ジオヅム": ("Naclstack", 933),
    "キョジオーン": ("Garganacl", 934),
    "カルボウ": ("Charcadet", 935),
    "グレンアルマ": ("Armarouge", 936),
    "ソウブレイズ": ("Ceruledge", 937),
    "ズピカ": ("Tadbulb", 938),
    "ハラバリー": ("Bellibolt", 939),
    "カイデン": ("Wattrel", 940),
    "タイカイデン": ("Kilowattrel", 941),
    "オラチフ": ("Maschiff", 942),
    "マフィティフ": ("Mabosstiff", 943),
    "シルシュルー": ("Shroodle", 944),
    "タギングル": ("Grafaiai", 945),
    "アノクサ": ("Bramblin", 946),
    "アノホラグサ": ("Brambleghast", 947),
    "ノノクラゲ": ("Toedscool", 948),
    "リククラゲ": ("Toedscruel", 949),
    "ガケガニ": ("Klawf", 950),
    "カプサイジ": ("Capsakid", 951),
    "スコヴィラン": ("Scovillain", 952),
    "シガロコ": ("Rellor", 953),
    "ベラカス": ("Rabsca", 954),
    "ヒラヒナ": ("Flittle", 955),
    "クエスパトラ": ("Espathra", 956),
    "カヌチャン": ("Tinkatink", 957),
    "ナカヌチャン": ("Tinkatuff", 958),
    "デカヌチャン": ("Tinkaton", 959),
    "ウミディグダ": ("Wiglett", 960),
    "ウミトリオ": ("Wugtrio", 961),
    "オトシドリ": ("Bombirdier", 962),
    "ナミイルカ": ("Finizen", 963),
    "イルカマン(ナイーブ)": ("Palafin (Zero)", 964),
    "イルカマン(マイティ)": ("Palafin (Hero)", 964),
    "ブロロン": ("Varoom", 965),
    "ブロロローム": ("Revavroom", 966),
    "モトトカゲ": ("Cyclizar", 967),
    "ミミズズ": ("Orthworm", 968),
    "キラーメ": ("Glimmet", 969),
    "キラフロル": ("Glimmora", 970),
    "ボチ": ("Greavard", 971),
    "ハカドッグ": ("Houndstone", 972),
    "カラミンゴ": ("Flamigo", 973),
    "アルクジラ": ("Cetoddle", 974),
    "ハルクジラ": ("Cetitan", 975),
    "ミガルーサ": ("Veluza", 976),
    "ヘイラッシャ": ("Dondozo", 977),
    "シャリタツ(そったすがた)": ("Tatsugiri (Curly)", 978),
    "シャリタツ(たれたすがた)": ("Tatsugiri (Droopy)", 978),
    "シャリタツ(のびたすがた)": ("Tatsugiri (Stretchy)", 978),
    "コノヨザル": ("Annihilape", 979),
    "ドオー": ("Clodsire", 980),
    "リキキリン": ("Farigiraf", 981),
    "ノココッチ": ("Dudunsparce", 982),
    "ドドゲザン": ("Kingambit", 983),
    "セビエ": ("Frigibax", 996),
    "セゴール": ("Arctibax", 997),
    "セグレイブ": ("Baxcalibur", 998),
    "コレクレー(とほ)": ("Gimmighoul (Roaming)", 999),
    "サーフゴー": ("Gholdengo", 1000),
    "ウネルミナモ": ("Walking Wake", 1009),
    "カミッチュ": ("Dipplin", 1011),
    "チャデス": ("Poltchageist", 1012),
    "ヤバソチャ": ("Sinistcha", 1013),
    "イイネイヌ": ("Okidogi", 1014),
    "マシマシラ": ("Munkidori", 1015),
    "キチキギス": ("Fezandipiti", 1016),
    "オーガポン(みどりのめん)": ("Ogerpon (Teal Mask)", 1017),
    "ブリジュラス": ("Archaludon", 1018),
    "カミツオロチ": ("Hydrapple", 1019),
    "モモワロウ": ("Pecharunt", 1025),
}


def find_by_japanese_name(
    name: str,
) -> PokemonNameEntry | None:
    """日本語名からポケモン情報を検索.

    Args:
        name: 日本語名

    Returns:
        見つかった場合はPokemonNameEntry、なければNone
    """
    entry = _POKEMON_NAME_MAP.get(name)
    if entry is None:
        return None
    name_en, dex = entry
    return PokemonNameEntry(name_ja=name, name_en=name_en, dex=dex)
